name: Prepare Action
description: Prepare an action for CICD

inputs:
  node-version:
    description: 'Node.js version to use'
    type: string
    required: true
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ github.pipeline }}-${{ github.ref }}
        path: node_modules
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-${{ github.pipeline }}-${{ github.ref }}