name: Build App 
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
        default: 22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use prepare-action
        uses: ./.github/prepare-action
        with:
          node-version: ${{ inputs.node-version }}

      - name: Build
        run: pnpm run generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .output/public