name: Build App 
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        default: 22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use prepare-action
        uses: ./.github/prepare-action
        with:
          node-version: 22

      - name: Build
        run: pnpm run generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .output/public