name: CI/CD Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      node-version: 22

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml



